### ISSUE TITLE
Deliver script to compile this into binary

### ISSUE THREAD

**Issue by schrmh** [sidorares/xclimsg#1]
In your repo there is no `xclimsg` binary but you show the usage of it in the README.md.
Looks like index.js uses node but I have no idea how to get a working binary with that.
Tried this:
```
npm install -g pkg
pkg index.js -o xclimsg
```
But then I get this when I try to run xclimsg:
```
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module './ext/big-requests'
Require stack:
- /snapshot/xclimsg/node_modules/x11/lib/xcore.js
- /snapshot/xclimsg/node_modules/x11/lib/index.js
- /snapshot/xclimsg/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at XClient.require (/snapshot/xclimsg/node_modules/x11/lib/xcore.js:538:14)
    at XClient.<anonymous> (/snapshot/xclimsg/node_modules/x11/lib/xcore.js:603:24)
    at XClient.emit (node:events:527:28)
    at /snapshot/xclimsg/node_modules/x11/lib/xcore.js:532:16 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/xclimsg/node_modules/x11/lib/xcore.js',
    '/snapshot/xclimsg/node_modules/x11/lib/index.js',
    '/snapshot/xclimsg/index.js'
  ],
  pkg: true

```

**Comment by schrmh** [comment]
Since forking is unavailable...:
https://github.com/schrmh/xclimsg/commit/c65457d012b33cc2b5db25e05233eb5efdada1fa

LLM gave me the build instructions which I then trimmed a bit. They are really awesome for close-to-zero documentation projects that assume people know every framework and all build instructions... Probably only wasted one or two hours on this project here due to missing build instructions, bigger projects with various other errors have been worse...
